name: flutter_template
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  async: ^2.9.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  easy_localization: ^3.0.1
  google_fonts: ^4.0.3
  formz: ^0.6.0
  flutter_svg: ^2.0.4
  hydrated_bloc: ^9.1.0
  bloc: ^8.1.1
  dartz: ^0.10.1
  cached_network_image: ^3.2.3
  flutter_blurhash: ^0.7.0
  auto_route: ^6.0.4
  permission_handler: ^10.2.0
  image_cropper: ^3.0.2
  flutter_native_image: ^0.0.6+1
  modal_bottom_sheet: ^2.1.2
  image_picker: ^0.8.7+1
  photo_manager: ^2.6.0
  logger: ^1.3.0
  path_provider: ^2.0.14
  device_info_plus: ^8.1.0

  dart_ipify: ^1.1.1
  webview_flutter: ^3.0.4
  webview_cookie_manager: ^2.0.6
  fk_user_agent: ^2.1.0
  url_launcher: ^6.1.10
  fl_chart: ^0.61.0
  flutter_onboarding_screen: ^2.0.2
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  
  flutter_localizations:
    sdk: flutter
  rename: ^2.1.1
  intl: ^0.17.0
  share_plus: ^6.3.2
  flutter_colorpicker: ^1.0.3
  qr_flutter: ^4.0.0
  sqflite: ^2.2.7
  onboarding: ^3.1.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^6.0.2
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_flavorizr: ^2.1.5
  flutter_gen_runner: ^5.1.0+1

flavorizr:
  app:
    android:
      flavorDimensions: 'flavor-type'
    ios:
  flavors:
    dev:
      app:
        name: '[DEV] Card'
        icon: 'assets/icons/launcher/app_icon.png'
      android:
        applicationId: 'com.fluttertemplate.dev'
      ios:
        bundleId: 'com.fluttertemplate.dev'
    qa:
      app:
        name: '[QA] Card '
        icon: 'assets/icons/launcher/app_icon.png'
      android:
        applicationId: 'com.fluttertemplate.qa'
      ios:
        bundleId: 'com.fluttertemplate.qa'
    staging:
      app:
        name: 'Card'
        icon: 'assets/icons/launcher/app_icon.png'
      android:
        applicationId: 'com.fluttertemplate.staging'
      ios:
        bundleId: 'com.fluttertemplate.staging'
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/launcher/
    - assets/images/
    - assets/locales/
    - assets/bioLink/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
